# Generated by Django 5.1.3 on 2024-11-22 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="user_birth",
            field=models.DateField(default=datetime.date(1997, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_email",
            field=models.EmailField(default="deafult@example.com", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_login_id",
            field=models.CharField(default="temp_login_id", max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(default="deafult User", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_nickname",
            field=models.CharField(default="Default Nickname", max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
