# Generated by Django 5.1.3 on 2024-12-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "calendar_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("color", models.CharField(max_length=7)),
                (
                    "invitation_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
