# Generated by Django 5.1.3 on 2024-11-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="start_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
    ]
