# Generated by Django 5.1.3 on 2024-11-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendar",
            name="id",
        ),
        migrations.AddField(
            model_name="calendar",
            name="calendar_id",
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
