# Generated by Django 5.1.3 on 2024-11-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0002_rename_date_event_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default="기본 설명"),
            preserve_default=False,
        ),
    ]
