# Generated by Django 5.1.3 on 2024-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarAdmin",
            fields=[
                ("admin_id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
