# Generated by Django 5.1.3 on 2024-11-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriteevent",
            name="description",
            field=models.CharField(default="기본값", max_length=255),
        ),
    ]
