# Generated by Django 5.1.3 on 2024-11-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="calendar",
            new_name="calendar_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="event",
            name="id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.AddField(
            model_name="event",
            name="admin_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
