# Generated by Django 5.1.3 on 2024-11-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0003_rename_calendar_event_calendar_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteEvent",
            fields=[
                (
                    "favorite_event_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("d_day", models.DateField(auto_now_add=True)),
                ("easy_insidebar", models.BooleanField(default=False)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
